language: python, cpp, java

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

jdk:
  - oraclejdk8
  - openjdk7

# command to run tests
script: nosetests
